### ISSUE TITLE
TypeError: Cannot read property 'members' of undefined

### ISSUE THREAD

**Issue by narigondelsiglo** [VulcanJS/Vulcan-Starter#1]
Hi Sacha, first of all: great work man!

We are trying to get working the new way of [two repo install](http://docs.vulcanjs.org/#Two-Repo-Install) (5 days old) that's forking this project as starting point (or by creating an empty meteor app), but when running meteor with the example-simple the following appears:

```
W20171004-11:30:40.823(-3)? (STDERR) TypeError: Cannot read property 'members' of undefined
W20171004-11:30:40.823(-3)? (STDERR)     at meteorInstall.node_modules.meteor.example-simple.lib.modules.movies.collection.js (packages/example-simple/lib/modules/movies/collection.js:40:1)
W20171004-11:30:40.824(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171004-11:30:40.825(-3)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171004-11:30:40.826(-3)? (STDERR)     at meteorInstall.node_modules.meteor.example-simple.lib.modules.index.js (packages/example-simple/lib/modules/index.js:1:14)
W20171004-11:30:40.826(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171004-11:30:40.827(-3)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171004-11:30:40.828(-3)? (STDERR)     at meteorInstall.node_modules.meteor.example-simple.lib.server.main.js (packages/example-simple/lib/server/main.js:1:14)
W20171004-11:30:40.829(-3)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171004-11:30:40.829(-3)? (STDERR)     at require (packages/modules-runtime.js:228:16)
```

Are we doing something wrong?

**Comment by SachaG** [comment]
I'll take a look, I still haven't fully adapted all examples for the upcoming Vulcan 1.8 release (make sure you're on the `devel` branch for the main Vulcan repo btw). So it's possible that something doesn't quite work yet.

**Comment by hammannja** [comment]
I was getting the same error, but have now been able to solve it. For me (I use a Windows environment), the first problem was setting the required Environment Variable.

1. What I believe finally worked was entering SET METEOR_PACKAGE_DIRS="~/Vulcan/packages", where "~" is replaced by a direct link to Vulcan/packages, which for me was "C:\Users\Jerry\Documents\dGit\Vulcan\packages."

2. Then, I restarted my computer.

3. Then I fixed some missing dependencies using "meteor npm install --save [missing dependencies identified by run script]. I believe there were two missing dependencies for me, the last of which was "cross-fetch."

Finally, it started working! Hopefully, this will help you! Jerry
