### ISSUE TITLE
Step 18 error when sorting

### ISSUE THREAD

**Issue by yannick-mayeur** [VulcanJS/Vulcan-Starter#140]
When uncommenting the line in the MovieApp2 component, the render of the list fails with: `Network error: Response not successful: Received status code 400`

The node server throws the following error:

```
I20191205-15:56:50.401(1)? { Error: GraphQL error: Variable "$input" got invalid value { limit: 20, enableTotal: true, enableCache: false, orderBy: { name: "asc" } }; Field "orderBy" is not defined by type MultiMovieInput.
I20191205-15:56:50.402(1)?     at new ApolloError (/home/yannick/Repos/Vulcan-Starter/node_modules/apollo-client/bundle.umd.js:92:26)
I20191205-15:56:50.402(1)?     at QueryData.getQueryResult (/home/yannick/Repos/Vulcan-Starter/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:363:17)
I20191205-15:56:50.402(1)?     at QueryData._this.getExecuteResult (/home/yannick/Repos/Vulcan-Starter/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:111:26)
I20191205-15:56:50.402(1)?     at RenderPromises.addQueryPromise (/home/yannick/Repos/Vulcan-Starter/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:939:12)
I20191205-15:56:50.402(1)?     at QueryData.getExecuteSsrResult (/home/yannick/Repos/Vulcan-Starter/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:237:44)
I20191205-15:56:50.402(1)?     at QueryData.execute (/home/yannick/Repos/Vulcan-Starter/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:160:17)
I20191205-15:56:50.402(1)?     at /home/yannick/Repos/Vulcan-Starter/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:509:55
I20191205-15:56:50.402(1)?     at useDeepMemo (/home/yannick/Repos/Vulcan-Starter/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:462:14)
I20191205-15:56:50.403(1)?     at useBaseQuery (/home/yannick/Repos/Vulcan-Starter/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:508:16)
I20191205-15:56:50.403(1)?     at useQuery (/home/yannick/Repos/Vulcan-Starter/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:526:10)
I20191205-15:56:50.403(1)?     at useMulti (packages/vulcan:core/lib/modules/containers/multi2.js:205:20)
I20191205-15:56:50.403(1)?     at Wrapped (packages/vulcan:core/lib/modules/containers/multi2.js:221:17)
I20191205-15:56:50.403(1)?     at processChild (/home/yannick/Repos/Vulcan-Starter/node_modules/react-dom/cjs/react-dom-server.node.development.js:3227:14)
I20191205-15:56:50.403(1)?     at resolve (/home/yannick/Repos/Vulcan-Starter/node_modules/react-dom/cjs/react-dom-server.node.development.js:3147:5)
I20191205-15:56:50.403(1)?     at ReactDOMServerRenderer.render (/home/yannick/Repos/Vulcan-Starter/node_modules/react-dom/cjs/react-dom-server.node.development.js:3631:22)
I20191205-15:56:50.403(1)?     at ReactDOMServerRenderer.read (/home/yannick/Repos/Vulcan-Starter/node_modules/react-dom/cjs/react-dom-server.node.development.js:3565:29)
I20191205-15:56:50.404(1)?     at renderToStaticMarkup (/home/yannick/Repos/Vulcan-Starter/node_modules/react-dom/cjs/react-dom-server.node.development.js:4312:27)
I20191205-15:56:50.404(1)?     at process (/home/yannick/Repos/Vulcan-Starter/node_modules/@apollo/react-ssr/lib/react-ssr.cjs.js:38:16)
I20191205-15:56:50.404(1)?     at /home/yannick/.meteor/packages/promise/.0.11.2.1nfm0ms.xv6b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by eric-burel** [comment]
@yannick-mayeur Can you please try to replace `orderBy` by `sort`?
You can check the schema using GraphQL Playground on the `/graphql` URL:
![image](https://user-images.githubusercontent.com/7983005/70426319-230f7c00-1a73-11ea-9fc7-1bf2a2511128.png)

Here you notice a `sort` field and no `orderBy` hence this issue (`orderBy` was probably used before the recent update of Vulcan).

**Comment by yannick-mayeur** [comment]
I will try that

**Comment by yannick-mayeur** [comment]
It seems to work when using `sort` instead of `orderBy` in the `MovieApp2` component.
But the `defaultInput` from `collection.js` has no effect even when using `sort`. Movies always first appear at the top of the list and then get to the bottom or to the position specified by the `MovieApp2` component.

**Comment by eric-burel** [comment]
See maybe https://github.com/VulcanJS/Vulcan/issues/2445? Now filtering/sorting is done by `mongoParams` and not by `collection.js` `getParameter` function, which is unused.

**Comment by yannick-mayeur** [comment]
So should this part be removed from the Starter and an example using `mongoParams` be added instead?

**Comment by eric-burel** [comment]
Yes but I don't think you'll be able to solve that directly. The issue is that the Datatable uses the old `multi` HOC, which in turns uses the old `getParamaters`. I think the solution is to use `multi2` in the datatable, in Vulcan core.
But you can at least open a PR that replace "orderBy" by "sort" if it does not explode and remove the error message
