### ISSUE TITLE
Weird logs and error on startup - getting-started

### ISSUE THREAD

**Issue by eric-burel** [VulcanJS/Vulcan-Starter#53]
Hi,

On a fresh install of, I get a long error message related to qraphQL schemas and maybe SSR. I have no idea what could cause this. Here is the full dump (it is long sorry). I am running on Meteor 1.6.1 and run the last version of Vulcan/Vulcan-Starter (01 may 2018, so 1.18.11 I guess).
I am stuck on step 9 (graphQL resolvers), so it seems related. Let me know if I can help debugging.

```
// fieldResolver
I20180501-17:28:35.579(2)? { '0': { [Function: require] extensions: [ '.js', '.json' ], resolve: [Function] },
I20180501-17:28:35.579(2)?   '1': 
I20180501-17:28:35.580(2)?    { executableSchema: 
I20180501-17:28:35.580(2)?       GraphQLSchema {
I20180501-17:28:35.580(2)?         _queryType: Query,
I20180501-17:28:35.580(2)?         _mutationType: Mutation,
I20180501-17:28:35.581(2)?         _subscriptionType: null,
I20180501-17:28:35.581(2)?         _directives: [Array],
I20180501-17:28:35.581(2)?         astNode: null,
I20180501-17:28:35.582(2)?         _typeMap: [Object],
I20180501-17:28:35.582(2)?         _implementations: {},
I20180501-17:28:35.583(2)?         _extensionsEnabled: true },
I20180501-17:28:35.583(2)?      [Symbol(__esModule)]: true },
I20180501-17:28:35.584(2)?   '2': 
I20180501-17:28:35.585(2)?    Module {
I20180501-17:28:35.586(2)?      id: '/node_modules/meteor/vulcan:lib/lib/server/apollo_server.js',
I20180501-17:28:35.587(2)?      children: 
I20180501-17:28:35.587(2)?       [ [Object],
I20180501-17:28:35.587(2)?         [Object],
I20180501-17:28:35.588(2)?         [Object],
I20180501-17:28:35.588(2)?         [Object],
I20180501-17:28:35.588(2)?         [Object],
I20180501-17:28:35.589(2)?         [Object],
I20180501-17:28:35.589(2)?         [Object],
I20180501-17:28:35.589(2)?         [Object],
I20180501-17:28:35.590(2)?         [Object],
I20180501-17:28:35.590(2)?         [Object],
I20180501-17:28:35.590(2)?         [Object],
I20180501-17:28:35.590(2)?         [Object],
I20180501-17:28:35.591(2)?         [Object],
I20180501-17:28:35.591(2)?         [Object],
I20180501-17:28:35.591(2)?         [Object],
I20180501-17:28:35.591(2)?         [Object],
I20180501-17:28:35.591(2)?         [Object],
I20180501-17:28:35.592(2)?         [Object],
I20180501-17:28:35.592(2)?         [Object],
I20180501-17:28:35.592(2)?         [Object],
I20180501-17:28:35.593(2)?         [Object] ],
I20180501-17:28:35.593(2)?      childrenById: 
I20180501-17:28:35.594(2)?       { '/node_modules/@babel/runtime/helpers/builtin/interopRequireDefault.js': [Object],
I20180501-17:28:35.594(2)?         '/node_modules/@babel/runtime/helpers/builtin/objectSpread.js': [Object],
I20180501-17:28:35.595(2)?         '/node_modules/apollo-server-express/package.json': [Object],
I20180501-17:28:35.596(2)?         '/node_modules/apollo-server-express/dist/index.js': [Object],
I20180501-17:28:35.598(2)?         '/node_modules/body-parser/index.js': [Object],
I20180501-17:28:35.598(2)?         '/node_modules/express/index.js': [Object],
I20180501-17:28:35.599(2)?         '/node_modules/graphql-tools/package.json': [Object],
I20180501-17:28:35.599(2)?         '/node_modules/graphql-tools/dist/index.js': [Object],
I20180501-17:28:35.599(2)?         '/node_modules/deepmerge/package.json': [Object],
I20180501-17:28:35.600(2)?         '/node_modules/deepmerge/dist/umd.js': [Object],
I20180501-17:28:35.600(2)?         '/node_modules/dataloader/package.json': [Object],
I20180501-17:28:35.600(2)?         '/node_modules/dataloader/index.js': [Object],
I20180501-17:28:35.601(2)?         '/node_modules/apollo-errors/package.json': [Object],
I20180501-17:28:35.601(2)?         '/node_modules/apollo-errors/dist/index.js': [Object],
I20180501-17:28:35.601(2)?         '/node_modules/compression/index.js': [Object],
I20180501-17:28:35.601(2)?         '/node_modules/meteor/meteor.js': [Object],
I20180501-17:28:35.601(2)?         '/node_modules/meteor/check/match.js': [Object],
I20180501-17:28:35.602(2)?         '/node_modules/meteor/accounts-base/server_main.js': [Object],
I20180501-17:28:35.602(2)?         '/node_modules/apollo-engine/package.json': [Object],
I20180501-17:28:35.602(2)?         '/node_modules/apollo-engine/lib/index.js': [Object],
I20180501-17:28:35.602(2)?         '/node_modules/meteor/vulcan:lib/lib/modules/graphql.js': [Object],
I20180501-17:28:35.603(2)?         '/node_modules/meteor/vulcan:lib/lib/modules/utils.js': [Object],
I20180501-17:28:35.603(2)?         '/node_modules/meteor/vulcan:lib/lib/server/meteor_patch.js': [Object],
I20180501-17:28:35.603(2)?         '/node_modules/meteor/vulcan:lib/lib/modules/settings.js': [Object],
I20180501-17:28:35.604(2)?         '/node_modules/meteor/vulcan:lib/lib/modules/collections.js': [Object],
I20180501-17:28:35.604(2)?         '/node_modules/meteor/vulcan:lib/lib/modules/findbyids.js': [Object],
I20180501-17:28:35.605(2)?         '/node_modules/meteor/vulcan:lib/lib/modules/callbacks.js': [Object] },
I20180501-17:28:35.605(2)?      parent: 
I20180501-17:28:35.606(2)?       Module {
I20180501-17:28:35.606(2)?         id: '/node_modules/meteor/vulcan:lib/lib/server/main.js',
I20180501-17:28:35.607(2)?         children: [Array],
I20180501-17:28:35.607(2)?         childrenById: [Object],
I20180501-17:28:35.607(2)?         parent: [Object],
I20180501-17:28:35.608(2)?         require: [Object],
I20180501-17:28:35.608(2)?         exports: [Object],
I20180501-17:28:35.608(2)?         loaded: true },
I20180501-17:28:35.609(2)?      require: { [Function: require] extensions: [Array], resolve: [Function] },
I20180501-17:28:35.609(2)?      exports: { executableSchema: [Object], [Symbol(__esModule)]: true },
I20180501-17:28:35.610(2)?      loaded: true },
I20180501-17:28:35.610(2)?   '3': '/node_modules/meteor/vulcan:lib/lib/server/apollo_server.js',
I20180501-17:28:35.611(2)?   '4': '/node_modules/meteor/vulcan:lib/lib/server' }
W20180501-17:28:35.611(2)? (STDERR) Error: Cannot return null for non-nullable field __Field.name.
W20180501-17:28:35.612(2)? (STDERR)     at completeValue (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:599:13)
W20180501-17:28:35.612(2)? (STDERR)     at completeValueWithLocatedError (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:546:21)
W20180501-17:28:35.612(2)? (STDERR)     at completeValueCatchingError (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:515:12)
W20180501-17:28:35.612(2)? (STDERR)     at resolveField (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:467:10)
W20180501-17:28:35.613(2)? (STDERR)     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:314:18
W20180501-17:28:35.613(2)? (STDERR)     at Array.reduce (<anonymous>)
W20180501-17:28:35.613(2)? (STDERR)     at executeFields (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:311:42)
W20180501-17:28:35.613(2)? (STDERR)     at collectAndExecuteSubfields (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:749:10)
W20180501-17:28:35.614(2)? (STDERR)     at completeObjectValue (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:731:10)
W20180501-17:28:35.614(2)? (STDERR)     at completeValue (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:628:12)
W20180501-17:28:35.614(2)? (STDERR)     at completeValue (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:597:21)
W20180501-17:28:35.614(2)? (STDERR)     at completeValueWithLocatedError (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:546:21)
W20180501-17:28:35.614(2)? (STDERR)     at completeValueCatchingError (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:515:12)
W20180501-17:28:35.615(2)? (STDERR)     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:651:25
W20180501-17:28:35.615(2)? (STDERR)     at Array.forEach (<anonymous>)
W20180501-17:28:35.615(2)? (STDERR)     at forEach (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/iterall/index.js:83:25)
W20180501-17:28:35.616(2)? (STDERR)     at completeListValue (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:647:24)
W20180501-17:28:35.616(2)? (STDERR)     at completeValue (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:611:12)
W20180501-17:28:35.617(2)? (STDERR)     at completeValueWithLocatedError (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:546:21)
W20180501-17:28:35.618(2)? (STDERR)     at completeValueCatchingError (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:521:21)
W20180501-17:28:35.619(2)? (STDERR)     at resolveField (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:467:10)
W20180501-17:28:35.619(2)? (STDERR)     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/graphql/execution/execute.js:314:18
I20180501-17:28:35.647(2)? url:  /
I20180501-17:28:35.647(2)? { Error: GraphQL error: Cannot return null for non-nullable field __Field.name.
I20180501-17:28:35.648(2)?     at new ApolloError (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/apollo-client/apollo.umd.js:1981:28)
I20180501-17:28:35.648(2)?     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/apollo-client/apollo.umd.js:3091:41
I20180501-17:28:35.648(2)?     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/apollo-client/apollo.umd.js:3583:25
I20180501-17:28:35.648(2)?     at Array.forEach (<anonymous>)
I20180501-17:28:35.649(2)?     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/apollo-client/apollo.umd.js:3580:27
I20180501-17:28:35.650(2)?     at Array.forEach (<anonymous>)
I20180501-17:28:35.650(2)?     at QueryManager.broadcastQueries (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/apollo-client/apollo.umd.js:3577:42)
I20180501-17:28:35.651(2)?     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/apollo-client/apollo.umd.js:3512:31
I20180501-17:28:35.652(2)?     at /home/eric-burel/.meteor/packages/promise/.0.10.2.1tr237d.jazx++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20180501-17:28:35.652(2)?  => awaited here:
I20180501-17:28:35.652(2)?     at Function.Promise.await (/home/eric-burel/.meteor/packages/promise/.0.10.2.1tr237d.jazx++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20180501-17:28:35.652(2)?     at Object.preRender (packages/vulcan:routing/lib/server/routing.jsx:57:14)
I20180501-17:28:35.653(2)?     at generateSSRData (packages/vulcan:routing/lib/server/router.jsx:53:15)
I20180501-17:28:35.653(2)?     at sendSSRHtml (packages/vulcan:routing/lib/server/router.jsx:87:45)
I20180501-17:28:35.654(2)?     at match (packages/vulcan:routing/lib/server/router.jsx:150:11)
I20180501-17:28:35.654(2)?     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/match.js:67:5
I20180501-17:28:35.654(2)?     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/createTransitionManager.js:108:11
I20180501-17:28:35.655(2)?     at done (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/AsyncUtils.js:79:19)
I20180501-17:28:35.655(2)?     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/AsyncUtils.js:85:7
I20180501-17:28:35.656(2)?     at getComponentsForRoute (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/getComponents.js:11:5)
I20180501-17:28:35.656(2)?     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/getComponents.js:35:5
I20180501-17:28:35.657(2)?     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/AsyncUtils.js:84:5
I20180501-17:28:35.657(2)?     at Array.forEach (<anonymous>)
I20180501-17:28:35.657(2)?     at mapAsync (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/AsyncUtils.js:83:9)
I20180501-17:28:35.658(2)?     at getComponents (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/getComponents.js:34:28)
I20180501-17:28:35.659(2)?     at finishEnterHooks (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/createTransitionManager.js:102:35)
I20180501-17:28:35.660(2)?     at runTransitionHooks (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/TransitionUtils.js:79:7)
I20180501-17:28:35.660(2)?     at runEnterHooks (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/TransitionUtils.js:112:12)
I20180501-17:28:35.661(2)?     at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/createTransitionManager.js:95:7
I20180501-17:28:35.661(2)?     at runTransitionHooks (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/TransitionUtils.js:79:7)
I20180501-17:28:35.662(2)?     at runChangeHooks (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/TransitionUtils.js:136:12)
I20180501-17:28:35.662(2)?     at finishMatch (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/createTransitionManager.js:92:5)
I20180501-17:28:35.662(2)?   graphQLErrors: 
I20180501-17:28:35.662(2)?    [ { message: 'Cannot return null for non-nullable field __Field.name.',
I20180501-17:28:35.662(2)?        locations: [Array],
I20180501-17:28:35.663(2)?        path: [Array] } ],
I20180501-17:28:35.663(2)?   networkError: null,
I20180501-17:28:35.663(2)?   message: 'GraphQL error: Cannot return null for non-nullable field __Field.name.',
I20180501-17:28:35.663(2)?   extraInfo: undefined,
I20180501-17:28:35.663(2)?   queryErrors: [ [Circular] ] }
W20180501-17:28:35.664(2)? (STDERR) 2018-05-01T15:28:35.647Z 'error while server-rendering' 'Error: GraphQL error: Cannot return null for non-nullable field __Field.name.\n    at new ApolloError (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/apollo-client/apollo.umd.js:1981:28)\n    at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/apollo-client/apollo.umd.js:3091:41\n    at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/apollo-client/apollo.umd.js:3583:25\n    at Array.forEach (<anonymous>)\n    at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/apollo-client/apollo.umd.js:3580:27\n    at Array.forEach (<anonymous>)\n    at QueryManager.broadcastQueries (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/apollo-client/apollo.umd.js:3577:42)\n    at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/apollo-client/apollo.umd.js:3512:31\n    at /home/eric-burel/.meteor/packages/promise/.0.10.2.1tr237d.jazx++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/home/eric-burel/.meteor/packages/promise/.0.10.2.1tr237d.jazx++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)\n    at Object.preRender (packages/vulcan:routing/lib/server/routing.jsx:57:14)\n    at generateSSRData (packages/vulcan:routing/lib/server/router.jsx:53:15)\n    at sendSSRHtml (packages/vulcan:routing/lib/server/router.jsx:87:45)\n    at match (packages/vulcan:routing/lib/server/router.jsx:150:11)\n    at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/match.js:67:5\n    at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/createTransitionManager.js:108:11\n    at done (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/AsyncUtils.js:79:19)\n    at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/AsyncUtils.js:85:7\n    at getComponentsForRoute (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/getComponents.js:11:5)\n    at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/getComponents.js:35:5\n    at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/AsyncUtils.js:84:5\n    at Array.forEach (<anonymous>)\n    at mapAsync (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/AsyncUtils.js:83:9)\n    at getComponents (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/getComponents.js:34:28)\n    at finishEnterHooks (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/createTransitionManager.js:102:35)\n    at runTransitionHooks (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/TransitionUtils.js:79:7)\n    at runEnterHooks (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/TransitionUtils.js:112:12)\n    at /home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/createTransitionManager.js:95:7\n    at runTransitionHooks (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/TransitionUtils.js:79:7)\n    at runChangeHooks (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/TransitionUtils.js:136:12)\n    at finishMatch (/home/eric-burel/Development/vulcan-starter-01-05-complete/node_modules/react-router/lib/createTransitionManager.js:92:5)'

```

**Comment by eric-burel** [comment]
Seems to be related to: [https://github.com/VulcanJS/Vulcan-Starter/issues/54](https://github.com/VulcanJS/Vulcan-Starter/issues/54)
```
"query MutationResolvers {
  __type(name: "Mutation") {
    fields {
      name
    }
  }
}
"
```

returns 
```
[{"data":{"__type":{"fields":null}},"errors":[{"message":"Cannot return null for non-nullable field __Field.name.","locations":[{"line":4,"column":7}],"path":["__type","fields",0,"name"]}],"extensions":{"tracing":{"version":1,"startTime":"2018-05-01T16:16:32.051Z","endTime":"2018-05-01T16:16:32.054Z","duration":3245259,"execution":{"resolvers":[]}},"cacheControl":{"version":1,"hints":[]}}}]
```

**Comment by SachaG** [comment]
I've seen that `Cannot return null for non-nullable field` error before I think, but I don't really remember what it was about exactly. Maybe you could inspect your GraphQL schema and query to see if there's any discrepancies?

**Comment by eric-burel** [comment]
@SachaG could you give me an example of the correct graphQL schema, maybe the one you get in the dump at some previous step of the tuto (6, 7) ? I am not much familiar with GraphQL yet but I don't remember having seen a schema for Resolvers or Mutations so it might be the issue

**Comment by SachaG** [comment]
Sure: 

```
scalar JSON
scalar Date

# A user object
type User {
  _id: String
  username: String
  createdAt: Date
  isAdmin: Boolean
  profile: JSON
  services: JSON
  displayName: String
  bio: String
  email: String
  emailHash: String
  avatarUrl: String
  htmlBio: String
  karma: Float
  slug: String
  website: String
  twitterUsername: String
  groups: [String]
  pageUrl: String
  editUrl: String
}

# A user object (input type)
input UsersInput {
  username: String
  isAdmin: Boolean
  profile: JSON
  displayName: String
  bio: String
  email: String
  website: String
  twitterUsername: String
  groups: [String]
}

# A user object (unset input type)
input UsersUnset {
  username: Boolean
  isAdmin: Boolean
  profile: Boolean
  displayName: Boolean
  bio: Boolean
  email: Boolean
  website: Boolean
  twitterUsername: Boolean
  groups: Boolean
}

# Type for Settings
type Setting {
  name: String
  value: JSON
  defaultValue: JSON
  isPublic: Boolean
  description: String
}

# Type for Callbacks
type Callback {
  name: String
  arguments: [JSON]
  runs: String
  newSyntax: Boolean
  returns: String
  description: String
  hooks: [String]
}

# Type for Movies
type Movie {
  _id: String
  createdAt: Date
  userId: String
  name: String
  review: String
}

# Type for Movies (input type)
input MoviesInput {
  name: String
  review: String
}

# Type for Movies (unset input type)
input MoviesUnset {
  name: Boolean
  review: Boolean
}

type Site {
  title: String
  url: String
  logoUrl: String
}

type Query {

  SiteData: Site
  
  UsersList(
    # A JSON object that contains the query terms used to fetch data
    terms: JSON, 
    # How much to offset the results by
    offset: Int, 
    # A limit for the query
    limit: Int, 
    # Whether to enable caching for this query
    enableCache: Boolean
  ): [User]
  
  UsersSingle(
    # The document's unique ID
    documentId: String, 
    # A unique slug identifying the document
    slug: String, 
    # Whether to enable caching for this query
    enableCache: Boolean
  ): User
  
  UsersTotal(
    # A JSON object that contains the query terms used to fetch data
    terms: JSON,
    # Whether to enable caching for this query
    enableCache: Boolean
  ): Int
  
  currentUser: User
  
  SettingsList(
    # A JSON object that contains the query terms used to fetch data
    terms: JSON, 
    # How much to offset the results by
    offset: Int, 
    # A limit for the query
    limit: Int, 
    # Whether to enable caching for this query
    enableCache: Boolean
  ): [Setting]
  
  SettingsTotal(
    # A JSON object that contains the query terms used to fetch data
    terms: JSON,
    # Whether to enable caching for this query
    enableCache: Boolean
  ): Int
  
  CallbacksList(
    # A JSON object that contains the query terms used to fetch data
    terms: JSON, 
    # How much to offset the results by
    offset: Int, 
    # A limit for the query
    limit: Int, 
    # Whether to enable caching for this query
    enableCache: Boolean
  ): [Callback]
  
  CallbacksTotal(
    # A JSON object that contains the query terms used to fetch data
    terms: JSON,
    # Whether to enable caching for this query
    enableCache: Boolean
  ): Int
  
  # A list of Movies documents matching a set of query terms
  MoviesList(
    # A JSON object that contains the query terms used to fetch data
    terms: JSON, 
    # How much to offset the results by
    offset: Int, 
    # A limit for the query
    limit: Int, 
    # Whether to enable caching for this query
    enableCache: Boolean
  ): [Movie]
  
  # A single Movies document fetched by ID or slug
  MoviesSingle(
    # The document's unique ID
    documentId: String, 
    # A unique slug identifying the document
    slug: String, 
    # Whether to enable caching for this query
    enableCache: Boolean
  ): Movie
  
  # The total count of Movies documents matching a set of query terms
  MoviesTotal(
    # A JSON object that contains the query terms used to fetch data
    terms: JSON,
    # Whether to enable caching for this query
    enableCache: Boolean
  ): Int
  
  SchemaContents: String
  
  MoviesCount: Int
  
}

type Mutation {

  usersNew(
    # The document to insert
    document: UsersInput
  ) : User

  usersEdit(
    # The unique ID of the document to edit
    documentId: String, 
    # An array of fields to insert
    set: UsersInput, 
    # An array of fields to delete
    unset: UsersUnset
  ) : User

  usersRemove(
    # The unique ID of the document to delete
    documentId: String
  ) : User

}
```

**Comment by eric-burel** [comment]
Thanks! I'll investigate this more deeply when I have access to my Ubuntu

**Comment by eric-burel** [comment]
So far it seems that the schemas have no name, so the introspecting requests that get the Resolvers and Queries does not work.

This request:

```
{
  __schema {
    types {
      name
    }
  }
}
```
will give:
```
{
  "data": {
    "__schema": {
      "types": [
        {
          "name": null
        },
        {
          "name": null
        },
        {
          "name": null
        },
        {
          "name": null
        },
        {
          "name": null
        },
# so on for each type in  the schema
...

 "extensions": {
    "tracing": {
      "version": 1,
      "startTime": "2018-05-02T16:54:34.967Z",
      "endTime": "2018-05-02T16:54:35.034Z",
      "duration": 66566584,
      "execution": {
        "resolvers": []
      }
    },
    "cacheControl": {
      "version": 1,
      "hints": []
    }
  }
```

so the following request for MutationResolvers will fail because name is `null` but the field is not supposed to be nullable (same goes for queries)
```
query MutationResolvers {
  __type(name: "Mutation") {
    fields {
      name
    }
  }
}
```
