### ISSUE TITLE
Bug when running Forum Example with latest vulcan (Latest commit 973b2bf)

### ISSUE THREAD

**Issue by adalidda** [VulcanJS/Vulcan-Starter#62]
Hi,

When I run the forum example with the latest Vulcan (Latest commit 973b2bf a day ago), I got the following error:

W20180622-15:13:17.903(7)? (STDERR) /home/kauprey/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180622-15:13:17.912(7)? (STDERR) 						throw(ex);
W20180622-15:13:17.912(7)? (STDERR) 						^
W20180622-15:13:17.913(7)? (STDERR) GraphQLError: Syntax Error GraphQL request (5:5) Unexpected Name "null"
W20180622-15:13:17.913(7)? (STDERR) 
W20180622-15:13:17.913(7)? (STDERR) 4:       }
W20180622-15:13:17.913(7)? (STDERR) 5:     null
W20180622-15:13:17.915(7)? (STDERR)        ^
W20180622-15:13:17.915(7)? (STDERR) 
W20180622-15:13:17.915(7)? (STDERR)     at syntaxError (/home/kauprey/adalidda-V4.4.x/node_modules/graphql/error/syntaxError.js:31:15)
W20180622-15:13:17.918(7)? (STDERR)     at unexpected (/home/kauprey/adalidda-V4.4.x/node_modules/graphql/language/parser.js:996:33)
W20180622-15:13:17.919(7)? (STDERR)     at parseDefinition (/home/kauprey/adalidda-V4.4.x/node_modules/graphql/language/parser.js:155:9)
W20180622-15:13:17.919(7)? (STDERR)     at parseDocument (/home/kauprey/adalidda-V4.4.x/node_modules/graphql/language/parser.js:109:22)
W20180622-15:13:17.920(7)? (STDERR)     at parse (/home/kauprey/adalidda-V4.4.x/node_modules/graphql/language/parser.js:46:10)
W20180622-15:13:17.920(7)? (STDERR)     at parseDocument (/home/kauprey/adalidda-V4.4.x/node_modules/graphql-tag/lib/graphql-tag.umd.js:134:16)
W20180622-15:13:17.920(7)? (STDERR)     at gql (/home/kauprey/adalidda-V4.4.x/node_modules/graphql-tag/lib/graphql-tag.umd.js:167:10)
W20180622-15:13:17.921(7)? (STDERR)     at withMutation (packages/vulcan:core/lib/modules/containers/withMutation.js:45:22)
W20180622-15:13:17.922(7)? (STDERR)     at NewsletterSubscribe.jsx (packages/vulcan:newsletter/lib/components/NewsletterSubscribe.jsx:58:63)
W20180622-15:13:17.923(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180622-15:13:17.923(7)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180622-15:13:17.923(7)? (STDERR)     at index.js (packages/vulcan:newsletter/lib/modules/index.js:1:220)
W20180622-15:13:17.925(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180622-15:13:17.925(7)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180622-15:13:17.925(7)? (STDERR)     at main.js (packages/vulcan:newsletter/lib/server/main.js:1:30)
W20180622-15:13:17.925(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:339:7)
W20180622-15:13:17.926(7)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180622-15:13:17.926(7)? (STDERR)     at /home/kauprey/adalidda-V4.4.x/.meteor/local/build/programs/server/packages/vulcan_newsletter.js:1319:15
W20180622-15:13:17.929(7)? (STDERR)     at /home/kauprey/adalidda-V4.4.x/.meteor/local/build/programs/server/packages/vulcan_newsletter.js:1324:3
W20180622-15:13:17.929(7)? (STDERR)     at /home/kauprey/adalidda-V4.4.x/.meteor/local/build/programs/server/boot.js:411:36
W20180622-15:13:17.932(7)? (STDERR)     at Array.forEach (<anonymous>)
W20180622-15:13:17.936(7)? (STDERR)     at /home/kauprey/adalidda-V4.4.x/.meteor/local/build/programs/server/boot.js:220:19
=> Exited with code: 1
W20180622-15:13:34.734(7)? (STDERR)           
W20180622-15:13:34.735(7)? (STDERR) /home/kauprey/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180622-15:13:34.741(7)? (STDERR) 						throw(ex);
W20180622-15:13:34.742(7)? (STDERR) 						^
W20180622-15:13:35.302(7)? (STDERR) GraphQLError: Syntax Error GraphQL request (5:5) Unexpected Name "null"
W20180622-15:13:35.303(7)? (STDERR) 
W20180622-15:13:35.303(7)? (STDERR) 4:       }
W20180622-15:13:35.304(7)? (STDERR) 5:     null
W20180622-15:13:35.304(7)? (STDERR)        ^
W20180622-15:13:35.305(7)? (STDERR) 
W20180622-15:13:35.305(7)? (STDERR)     at syntaxError (/home/kauprey/adalidda-V4.4.x/node_modules/graphql/error/syntaxError.js:31:15)

Thank You
Adalidda

**Comment by adalidda** [comment]
Issue fixed with Latest commit f60f0b1.

Run the following command after npm install
meteor npm install @babel/runtime@latest
