### ISSUE TITLE
Getting error: Fragment "UsersCurrent" registered, but not initialized

### ISSUE THREAD

**Issue by wfsaxton** [VulcanJS/Vulcan-Starter#7]
I followed the complete installation instructions in the README and am getting the following error when I attempt to bring up the server:

```
➜  myVulcan git:(master) ✗ meteor --port 3000 --settings settings.json
[[[[[ ~/projects/myVulcan ]]]]]               

=> Started proxy.                             
=> Meteor 1.6 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
W20171109-13:18:57.562(-5)? (STDERR) Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
W20171109-13:18:57.602(-5)? (STDERR) Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
W20171109-13:18:57.603(-5)? (STDERR) /home/wfsaxton/.meteor/packages/meteor-tool/.1.5.2_2.1cp2v59.uaag++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171109-13:18:57.604(-5)? (STDERR) 						throw(ex);
W20171109-13:18:57.605(-5)? (STDERR) 						^
W20171109-13:18:57.606(-5)? (STDERR) 
W20171109-13:18:57.607(-5)? (STDERR) Error: Fragment "UsersCurrent" registered, but not initialized.
W20171109-13:18:57.608(-5)? (STDERR)     at getFragment (packages/vulcan:lib/lib/modules/fragments.js:161:11)
W20171109-13:18:57.609(-5)? (STDERR)     at withCurrentUser (packages/vulcan:core/lib/modules/containers/withCurrentUser.js:15:9)
W20171109-13:18:57.609(-5)? (STDERR)     at meteorInstall.node_modules.meteor.vulcan:forms.lib.FormWrapper.jsx (packages/vulcan:forms/lib/FormWrapper.jsx:223:16)
W20171109-13:18:57.610(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171109-13:18:57.611(-5)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171109-13:18:57.612(-5)? (STDERR)     at meteorInstall.node_modules.meteor.vulcan:forms.lib.export.js (packages/vulcan:forms/lib/export.js:1:228)
W20171109-13:18:57.613(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171109-13:18:57.614(-5)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171109-13:18:57.615(-5)? (STDERR)     at /home/wfsaxton/projects/myVulcan/.meteor/local/build/programs/server/packages/vulcan_forms.js:2121:15
W20171109-13:18:57.616(-5)? (STDERR)     at /home/wfsaxton/projects/myVulcan/.meteor/local/build/programs/server/packages/vulcan_forms.js:2127:3
=> Exited with code: 1

```

**Comment by wfsaxton** [comment]
The first "test" goes fine, although it does have the same warning messages:

```
=> App running at: http://localhost:3033/
W20171109-13:26:37.295(-5)? (STDERR) Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class
W20171109-13:26:37.296(-5)? (STDERR) Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
W20171109-13:26:37.296(-5)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20171109-13:26:37.297(-5)? (STDERR) While this implementation will work correctly, it is known to be
W20171109-13:26:37.297(-5)? (STDERR) approximately three times slower than the native implementation.
W20171109-13:26:37.299(-5)? (STDERR) In order to use the native implementation instead, run
W20171109-13:26:37.299(-5)? (STDERR) 
W20171109-13:26:37.300(-5)? (STDERR)   meteor npm install --save bcrypt
W20171109-13:26:37.300(-5)? (STDERR) 
W20171109-13:26:37.301(-5)? (STDERR) in the root directory of your application.

```

**Comment by wfsaxton** [comment]
Not sure what the issue was, but I re-ran the instructions again and the error seems to have cleared up.
