### ISSUE TITLE
Example-Forum error on subscribe

### ISSUE THREAD

**Issue by jesperordrup** [VulcanJS/Vulcan-Starter#75]
On startpage when trying to subscribe I get the following error:

I20180812-17:45:53.905(2)? // Adding xxxx@yyyyy.dk to mailchimp list…
W20180812-17:45:53.905(2)? (STDERR) TypeError: Cannot read property 'subscribe' of undefined
W20180812-17:45:53.906(2)? (STDERR)     at Promise.asyncApply (packages/vulcan:newsletter/lib/server/newsletters.js:47:40)
W20180812-17:45:53.906(2)? (STDERR)     at /Users/jesper/.meteor/packages/promise/.0.11.1.1umxhu2.jv7l++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20180812-17:45:53.906(2)? (STDERR)  => awaited here:
W20180812-17:45:53.906(2)? (STDERR)     at Function.Promise.await (/Users/jesper/.meteor/packages/promise/.0.11.1.1umxhu2.jv7l++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20180812-17:45:53.907(2)? (STDERR)     at Promise.asyncApply (packages/vulcan:newsletter/lib/server/mutations.js:31:7)
W20180812-17:45:53.907(2)? (STDERR)     at /Users/jesper/.meteor/packages/promise/.0.11.1.1umxhu2.jv7l++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40

**Comment by PaulDreef** [comment]
Me too...
