### ISSUE TITLE
fresh install - Fragment "UsersCurrent" registered, but not initialized.

### ISSUE THREAD

**Issue by yancoupro** [VulcanJS/Vulcan-Starter#8]
Hi, 

I run the steps from the README and I get this error at the last step. 
```
W20171111-10:35:31.616(-5)? (STDERR) Error: Fragment "UsersCurrent" registered, but not initialized.
W20171111-10:35:31.617(-5)? (STDERR)     at getFragment (packages/vulcan:lib/lib/modules/fragments.js:161:11)
W20171111-10:35:31.619(-5)? (STDERR)     at withCurrentUser (packages/vulcan:core/lib/modules/containers/withCurrentUser.js:15:9)
W20171111-10:35:31.619(-5)? (STDERR)     at meteorInstall.node_modules.meteor.vulcan:forms.lib.FormWrapper.jsx (packages/vulcan:forms/lib/FormWrapper.jsx:223:16)
W20171111-10:35:31.620(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171111-10:35:31.620(-5)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171111-10:35:31.621(-5)? (STDERR)     at meteorInstall.node_modules.meteor.vulcan:forms.lib.export.js (packages/vulcan:forms/lib/export.js:1:228)
W20171111-10:35:31.622(-5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171111-10:35:31.622(-5)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171111-10:35:31.623(-5)? (STDERR)     at /Users/user/sandbox/vulcan/alpha/client/web/.meteor/local/build/programs/server/packages/vulcan_forms.js:2121:15
W20171111-10:35:31.623(-5)? (STDERR)     at /Users/user/sandbox/vulcan/alpha/client/web/.meteor/local/build/programs/server/packages/vulcan_forms.js:2127:3
```

I found this blog post for help, but don’t know where to start. 
https://blog.vulcanjs.org/vulcanjs-1-8-a-better-architecture-2eef7375e6f1

Thanks

**Comment by yancoupro** [comment]
sorry for bothering you, I upgraded, and redid the process from scratch and it works.
