### ISSUE TITLE
Example-forum 1.12.3: GraphQL error: Cannot read property 'postedAt' of undefined

### ISSUE THREAD

**Issue by calinn** [VulcanJS/Vulcan-Starter#80]
When I'm going to insert a new post or edit a post, after I clicked submit button, it shows: 

```
TypeError: Cannot read property 'postedAt' of undefined
W20180903-17:00:33.205(-5)? (STDERR)     at Object.onCreate (packages/example-forum/lib/modules/posts/schema.js:62:17)
W20180903-17:00:33.205(-5)? (STDERR)     at Promise.asyncApply (packages/vulcan:lib/lib/server/mutators.js:93:43)
W20180903-17:00:33.206(-5)? (STDERR)     at C:\Users\Carlos\AppData\Local\.meteor\packages\promise\0.11.1\npm\node_modules\meteor-promise\fiber_pool.js:43:40
W20180903-17:00:33.206(-5)? (STDERR)  => awaited here:
W20180903-17:00:33.207(-5)? (STDERR)     at Function.Promise.await (C:\Users\Carlos\AppData\Local\.meteor\packages\promise\0.11.1\npm\node_modules\meteor-promise\promise_server.js:56:12)
W20180903-17:00:33.207(-5)? (STDERR)     at Promise.asyncApply (packages/vulcan:core/lib/modules/default_mutations.js:58:9)
W20180903-17:00:33.207(-5)? (STDERR)     at C:\Users\Carlos\AppData\Local\.meteor\packages\promise\0.11.1\npm\node_modules\meteor-promise\fiber_pool.js:43:40
```

**Comment by SachaG** [comment]
Are you using the latest versions of both Vulcan core packages and the Starter repo?
