### ISSUE TITLE
Getting Started Step 16

### ISSUE THREAD

**Issue by dakratz** [VulcanJS/Vulcan-Starter#87]
I was running through the getting started tutorial.

Uncommenting the MoviesApp2 import as per the instructions breaks the application.  The surfaced exception is:

2018-09-14T19:19:11.377Z 'error while server-rendering' 'ReferenceError: withMulti is not defined\n    at Datatable.render (packages/vulcan:core/lib/modules/components/Datatable.jsx:75:33)\n    at walkTree (/home/dkratz/dev/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:709:32)\n    at walkTree (/home/dkratz/dev/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:719:13)\n    at /home/dkratz/dev/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:729:21\n    at forEachSingleChild (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:881:8)\n    at traverseAllChildrenImpl (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:785:5)\n    at traverseAllChildrenImpl (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:801:23)\n    at traverseAllChildren (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:856:10)\n    at Object.forEachChildren [as forEach] (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:901:3)\n    at walkTree (/home/dkratz/dev/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:727:28)\n    at /home/dkratz/dev/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:729:21\n    at forEachSingleChild (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:881:8)\n    at traverseAllChildrenImpl (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:785:5)\n    at traverseAllChildren (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:856:10)\n    at Object.forEachChildren [as forEach] (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:901:3)\n    at walkTree (/home/dkratz/dev/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:727:28)\n    at walkTree (/home/dkratz/dev/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:719:13)\n    at /home/dkratz/dev/Vulcan-Starter/node_modules/react-apollo/react-apollo.umd.js:729:21\n    at forEachSingleChild (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:881:8)\n    at traverseAllChildrenImpl (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:785:5)\n    at traverseAllChildrenImpl (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:801:23)\n    at traverseAllChildren (/home/dkratz/dev/Vulcan-Starter/node_modules/react/cjs/react.development.js:856:10)\n => awaited here:\n    at Function.Promise.await (/home/dkratz/.meteor/packages/promise/.0.11.1.ihl06c.0g81b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)\n    at Object.preRender (packages/vulcan:routing/lib/server/routing.jsx:58:14)\n    at generateSSRData (packages/vulcan:routing/lib/server/router.jsx:53:15)\n    at sendSSRHtml (packages/vulcan:routing/lib/server/router.jsx:87:45)\n    at match (packages/vulcan:routing/lib/server/router.jsx:150:11)\n    at /home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/match.js:67:5\n    at /home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/createTransitionManager.js:108:11\n    at done (/home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/AsyncUtils.js:79:19)\n    at /home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/AsyncUtils.js:85:7\n    at getComponentsForRoute (/home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/getComponents.js:11:5)\n    at /home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/getComponents.js:35:5\n    at /home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/AsyncUtils.js:84:5\n    at Array.forEach (<anonymous>)\n    at mapAsync (/home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/AsyncUtils.js:83:9)\n    at getComponents (/home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/getComponents.js:34:28)\n    at finishEnterHooks (/home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/createTransitionManager.js:102:35)\n    at runTransitionHooks (/home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/TransitionUtils.js:79:7)\n    at runEnterHooks (/home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/TransitionUtils.js:112:12)\n    at /home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/createTransitionManager.js:95:7\n    at runTransitionHooks (/home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/TransitionUtils.js:79:7)\n    at runChangeHooks (/home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/TransitionUtils.js:136:12)\n    at finishMatch (/home/dkratz/dev/Vulcan-Starter/node_modules/react-router/lib/createTransitionManager.js:92:5)'

**Comment by dakratz** [comment]
I was able to get past the issue by switching to the two repository install method.

**Comment by eric-burel** [comment]
Should be solved now we updated Vulcan
